"""add_cascading_delete

Revision ID: ae1f0c7201f7
Revises: 53d782754786
Create Date: 2026-02-07 18:00:59.747117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ae1f0c7201f7'
down_revision: Union[str, Sequence[str], None] = '53d782754786'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('bookmarks_post_id_fkey'), 'bookmarks', type_='foreignkey')
    op.drop_constraint(op.f('bookmarks_owner_id_fkey'), 'bookmarks', type_='foreignkey')
    op.create_foreign_key(None, 'bookmarks', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'bookmarks', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('emails_verifications_user_id_fkey'), 'emails_verifications', type_='foreignkey')
    op.create_foreign_key(None, 'emails_verifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('likes', 'author_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('likes_post_id_fkey'), 'likes', type_='foreignkey')
    op.drop_constraint(op.f('likes_author_id_fkey'), 'likes', type_='foreignkey')
    op.create_foreign_key(None, 'likes', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'likes', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('posts_author_id_fkey'), 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('profiles_user_id_fkey'), 'profiles', type_='foreignkey')
    op.create_foreign_key(None, 'profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('relations_sender_id_fkey'), 'relations', type_='foreignkey')
    op.drop_constraint(op.f('relations_receiver_id_fkey'), 'relations', type_='foreignkey')
    op.create_foreign_key(None, 'relations', 'users', ['receiver_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'relations', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('replies_post_id_fkey'), 'replies', type_='foreignkey')
    op.drop_constraint(op.f('replies_author_id_fkey'), 'replies', type_='foreignkey')
    op.create_foreign_key(None, 'replies', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'replies', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'replies', type_='foreignkey')
    op.drop_constraint(None, 'replies', type_='foreignkey')
    op.create_foreign_key(op.f('replies_author_id_fkey'), 'replies', 'users', ['author_id'], ['id'])
    op.create_foreign_key(op.f('replies_post_id_fkey'), 'replies', 'posts', ['post_id'], ['id'])
    op.drop_constraint(None, 'relations', type_='foreignkey')
    op.drop_constraint(None, 'relations', type_='foreignkey')
    op.create_foreign_key(op.f('relations_receiver_id_fkey'), 'relations', 'users', ['receiver_id'], ['id'])
    op.create_foreign_key(op.f('relations_sender_id_fkey'), 'relations', 'users', ['sender_id'], ['id'])
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.create_foreign_key(op.f('profiles_user_id_fkey'), 'profiles', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(op.f('posts_author_id_fkey'), 'posts', 'users', ['author_id'], ['id'])
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.create_foreign_key(op.f('likes_author_id_fkey'), 'likes', 'users', ['author_id'], ['id'])
    op.create_foreign_key(op.f('likes_post_id_fkey'), 'likes', 'posts', ['post_id'], ['id'])
    op.alter_column('likes', 'author_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'emails_verifications', type_='foreignkey')
    op.create_foreign_key(op.f('emails_verifications_user_id_fkey'), 'emails_verifications', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'bookmarks', type_='foreignkey')
    op.drop_constraint(None, 'bookmarks', type_='foreignkey')
    op.create_foreign_key(op.f('bookmarks_owner_id_fkey'), 'bookmarks', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(op.f('bookmarks_post_id_fkey'), 'bookmarks', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###
