"""add_media_fields_for_posts

Revision ID: d182e8d3ce3e
Revises: e17936c0712e
Create Date: 2026-02-11 15:07:51.068885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd182e8d3ce3e'
down_revision: Union[str, Sequence[str], None] = 'e17936c0712e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('media_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('posts', sa.Column('media_public_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('posts', sa.Column('media_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('posts', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('posts', 'media_type')
    op.drop_column('posts', 'media_public_id')
    op.drop_column('posts', 'media_url')
    # ### end Alembic commands ###
