"""add_enum_on_relation_status

Revision ID: e17936c0712e
Revises: cc585abd63a1
Create Date: 2026-02-09 23:52:54.605439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e17936c0712e'
down_revision: Union[str, Sequence[str], None] = 'cc585abd63a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relations', sa.Column('status', sa.String(), nullable=False))
    op.drop_column('relations', 'is_accepted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relations', sa.Column('is_accepted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('relations', 'status')
    # ### end Alembic commands ###
