"""

Revision ID: e706d7118346
Revises: 60323b503e71
Create Date: 2026-02-25 10:23:30.951799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e706d7118346'
down_revision: Union[str, Sequence[str], None] = '60323b503e71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relations', sa.Column('follower_id', sa.Uuid(), nullable=False))
    op.add_column('relations', sa.Column('following_id', sa.Uuid(), nullable=False))
    op.create_unique_constraint('unique_follow_relation', 'relations', ['follower_id', 'following_id'])
    op.drop_constraint(op.f('relations_sender_id_fkey'), 'relations', type_='foreignkey')
    op.drop_constraint(op.f('relations_receiver_id_fkey'), 'relations', type_='foreignkey')
    op.create_foreign_key(None, 'relations', 'users', ['following_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'relations', 'users', ['follower_id'], ['id'], ondelete='CASCADE')
    op.drop_column('relations', 'receiver_id')
    op.drop_column('relations', 'sender_id')
    op.drop_column('relations', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relations', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('relations', sa.Column('sender_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('relations', sa.Column('receiver_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'relations', type_='foreignkey')
    op.drop_constraint(None, 'relations', type_='foreignkey')
    op.create_foreign_key(op.f('relations_receiver_id_fkey'), 'relations', 'users', ['receiver_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('relations_sender_id_fkey'), 'relations', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('unique_follow_relation', 'relations', type_='unique')
    op.drop_column('relations', 'following_id')
    op.drop_column('relations', 'follower_id')
    # ### end Alembic commands ###
